apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: redhat-appstudio-qe 
  janus-idp.io/tekton: redhat-appstudio-qe
  backstage.io/kubernetes-id: redhat-appstudio-qe
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: redhat-appstudio-qe
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  