apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: redhat-appstudio-qe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: redhat-appstudio-qe 
  name: redhat-appstudio-qe
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: redhat-appstudio-qe
    weight: 100 
